# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspector', '0013_auto_20180802_2305'),
        ('dianzi_weilan', '0010_auto_20180701_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('proc_time', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('proc_status', models.CharField(choices=[('processed', '已处理'), ('unprocess', '未处理')], default='unprocess', max_length=30, verbose_name='处理状态')),
                ('proc_detail', models.TextField(blank=True, verbose_name='处理结果')),
                ('reason', models.CharField(blank=True, max_length=700, verbose_name='警告原因')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Inspector', verbose_name='监察员')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人员')),
            ],
        ),
    ]
